name: meditation
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  carousel_slider: ^4.1.1
  flutter_screenutil: ^5.3.1
  flutter_svg: ^1.1.1+1
  get: ^4.3.8
  flutter:
    sdk: flutter
  url_launcher: ^6.1.5

  cupertino_icons: ^1.0.2
  flutter_cube: ^0.1.1
  model_viewer: ^0.8.1
  animated_splash_screen: ^1.1.0
  lottie: ^1.2.1
  simple_animations: ^4.0.1
  supercharged: ^2.1.1
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path : "assets/images/tietlogo1.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/pics/
    - assets/pics/bgabout.png
    - assets/images/
    - assets/images/Core/
    - assets/3dobjects/
    - assets/3dobjects/Hostelc/
    - assets/3dobjects/Hostele/
    - assets/images/loading.json

